//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Arac
{
    public int AracSahibiID { get; set; }
    public string Plaka { get; set; }
    public int ModelNo { get; set; }
    public string Renk { get; set; }
    public bool active { get; set; }
}
